// import { Inter } from "next/font/google";
import { FC, PropsWithChildren } from "react";

import "./globals.css";
import { RootProvider } from "./RootProvider";

// const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
};

export default RootLayout;
export { metadata };
