// import { Inter } from "next/font/google";
import { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";

import { FC, PropsWithChildren } from "react";

// polyfill for(lvh svh dvh)
// @see https://github.com/joppuyo/large-small-dynamic-viewport-units-polyfill
import "large-small-dynamic-viewport-units-polyfill";

import "./globals.css";
import { RootProvider } from "./RootProvider";

// const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  // #region logic functions start
  // #endregion logic functions end
  return (
    <ViewTransitions>
      <html lang="en">
        {/* <body className={inter.className}>{children}</body> */}
        <body>
          <RootProvider>{children}</RootProvider>
        </body>
      </html>
    </ViewTransitions>
  );
};

export default RootLayout;
export { metadata };
